const Cardsdata = [
  {
    id: 1,
    rname: "Massala Theoryy",
    imgdata: "/images/img-01.avif",
    address: "North Indian, Biryani, Mughlai",
    somedata: " 1175 + order placed from here recently",
    price: 350,
    rating: "3.8",
    qnty: 0,
  },
  {
    id: 2,
    rname: "Jugaadi Adda",
    imgdata: "/images/img-02.avif",
    address: "Street Food",
    somedata: " 2525 + order placed from here recently",

    price: 25,
    rating: "3.9",
    qnty: 0,
  },
  {
    id: 3,
    rname: "La Milano Pizzeria",
    imgdata: "/images/img-03.avif",
    address: "Pizza, Fast Food, Pasta",
    somedata: " 650 + order placed from here recently",
    price: 70,
    rating: "4.2",
    qnty: 0,
  },
  {
    id: 4,
    rname: "Momoman",
    imgdata: "/images/img-04.avif",
    address: "Momos",
    somedata: " 300 + order placed from here recently",
    price: 70,
    rating: "3.8",
    qnty: 0,
  },
  {
    id: 5,
    rname: "Jassi De Parathe",
    imgdata: "/images/img-05.avif",
    address: "North Indian",
    somedata: "1050 + order placed from here recently",
    price: 210,
    rating: "4.0",
    qnty: 0,
  },
  {
    id: 6,
    rname: "Anjoy Latenight Meals",
    imgdata: "images/img-06.avif",
    address: "Wraps FastFood, Chines",
    somedata: " 1100 + order placed from here recently",
    price: 100,
    rating: "3.8",
    qnty: 0,
  },
  {
    id: 7,
    rname: "Hocco Eatery",
    imgdata: "/images/img-07.avif",
    address: "North Indian, Fast Food",
    somedata: "500 + order placed from here recently",
    price: 300,
    rating: "3.8",
    qnty: 0,
  },
  {
    id: 8,
    rname: "Chai Wai",
    imgdata: "/images/img-08.avif",
    address: "Tea, Coffee, Shake, Beverages",
    somedata: "500 + order placed from here recently",
    price: 100,
    rating: "3.2",
    qnty: 0,
  },
  {
    id: 9,
    rname: "HL Frankie",
    imgdata: "/images/img-09.avif",
    address: "Burger, Sandwich, Fast Food",
    somedata: "2525 + order placed from here recently",
    price: 100,
    rating: "3.8",
    qnty: 0,
  },
];
export default Cardsdata;
